#!/bin/bash

. ./hooks/env

# $IMAGE_NAME var is injected into the build so the tag is correct.
echo "[***] Pre build hook running"

# Build cpu dependencies
BASE=$IMAGE_NAME-$ROS_DISTRO-base
docker build -t $BASE -f Dockerfile.base ./../..
docker push $BASE

# Build cuda dependencies
BASE_CUDA=$BASE-cuda
docker build -t $BASE_CUDA --build-arg FROM_ARG=$BASE -f Dockerfile.cuda ./../..
docker push $BASE_CUDA